#PBS -q class
#PBS -l nodes=1:m2090
#PBS -l walltime=00:05:00
#PBS -N mbs

# Changes to the directory we were in when we
# submit the job:

cd $PBS_O_WORKDIR

# Runs a bunch of standard command-line
# utilities, just as an example:

echo "Script began:" `date`
echo "Node:" `hostname`
echo "Current directory: ${PWD}"

make clean
make -j10

./tsp usa13509_morton.tsp

echo ""
echo "=== Done! ==="

# eof
